stages:
  - build
  - deploy

docs-build:
  stage: build
  image:
    name: python:latest
  script:
    - pip install -e.[docs]
    - mkdocs build --site-dir build/docs/public
  artifacts:
    paths:
      - build/docs/public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    changes:
      paths:
        - docs/*

docs-deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$WWW_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no -r build/docs/public deploy-www@atopile.io:/var/www/docs
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        paths:
          - docs/*

build:
  stage: build
  image:
    # consider upgrading to a newer version of kaniko?
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:totally-a-tag"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  # rules:
  #   - if: $CI_COMMIT_TAG
