name: Continuous Delivery

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write

jobs:
  python:
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://pypi.org/p/atopile/
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v2

      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      -
        name: Make python package
        run: |
          pip install build twine
          python -m build

      -
        name: Upload Python Artifact
        uses: actions/upload-artifact@v2
        with:
          name: python-package
          path: dist

      -
        name: Publish package distributions to PyPI
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf
        with:
          repository-url: https://test.pypi.org/legacy/

  docker:
    runs-on: ubuntu-latest

    needs: python

    strategy:
      matrix:
        include:
          - dockerfile: "Dockerfile.ci"
            image: "atopile-ci"
          # FIXME: hush... soon my child
          # - dockerfile: "kicad"
          #   image: "atopile-kicad"

    steps:
      - uses: actions/checkout@v2

      -
        name: Download python-package
        uses: actions/download-artifact@v2
        with:
          name: python-package
          path: dist

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/atopile/${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      -
        name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
