name: CI

on: [push, pull_request]

jobs:
  cli-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -e ."[dev,test,docs]"


    - name: Run linter
      run: ruff src/atopile

  cli-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -e ."[dev,test,docs]"

    - name: Run tests
      run: pytest

    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-artifacts
        path: artifacts

  docs-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -e .[docs]
        pip install mkdocs

    - name: Build Documentation
      run: mkdocs build --site-dir build/docs/public

    - name: Upload Documentation Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: build/docs/public
