name: Do CI for atopile core

on: push

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -e ."[dev,test]"

    - name: Lint
      run: ruff src/atopile

    - name: Test
      run: pytest

    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-artifacts
        path: artifacts

  # build:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: stwets
  #       run: |
  #         pip install build
  #         asdfds
